# Generated by Django 5.0.6 on 2024-06-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_album_product_post_tags_customer_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
